#!/usr/bin/env bash
# =============================================================================
#  UnderHost One-Domain — Database Module
#  modules/database.sh
# =============================================================================

[[ -n "${_UH_DB_LOADED:-}" ]] && return 0
_UH_DB_LOADED=1

db_create() {
    step "Configuring MariaDB"

    # Secure MariaDB installation (idempotent)
    _db_secure_installation

    # Create database, user, and grant privileges
    _db_create_domain_db

    # Write /root/.my.cnf for passwordless root access (used by mysqldump, etc.)
    _db_write_my_cnf

    # Tune MariaDB
    _db_tune

    svc_reload mariadb
    ok "MariaDB configured: db=${DB_NAME} user=${DB_USER}"
}

_db_secure_installation() {
    # Use root socket auth on AlmaLinux, unix_socket on Debian/Ubuntu
    # Both allow root access without password; we protect via file perms.

    # Anonymous users
    mysql -e "DELETE FROM mysql.user WHERE User='';" 2>/dev/null || true
    # Remote root
    mysql -e "DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost','127.0.0.1','::1');" 2>/dev/null || true
    # Test database
    mysql -e "DROP DATABASE IF EXISTS test;" 2>/dev/null || true
    mysql -e "DELETE FROM mysql.db WHERE Db='test' OR Db='test\\_%';" 2>/dev/null || true
    mysql -e "FLUSH PRIVILEGES;" 2>/dev/null || true
    ok "MariaDB secured"
}

_db_create_domain_db() {
    # Check if DB already exists
    if mysql -e "SHOW DATABASES LIKE '${DB_NAME}';" 2>/dev/null | grep -q "${DB_NAME}"; then
        warn "Database '${DB_NAME}' already exists — skipping creation"
        return
    fi

    mysql <<EOSQL
CREATE DATABASE IF NOT EXISTS \`${DB_NAME}\` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS '${DB_USER}'@'localhost' IDENTIFIED BY '${DB_PASS}';
GRANT ALL PRIVILEGES ON \`${DB_NAME}\`.* TO '${DB_USER}'@'localhost';
FLUSH PRIVILEGES;
EOSQL

    ok "Created database: ${DB_NAME}"
    ok "Created user: ${DB_USER}@localhost"
}

_db_write_my_cnf() {
    # Write /root/.my.cnf — used by mysqldump and mysql CLI without password exposure
    cat > /root/.my.cnf <<EOF
# Generated by UnderHost One-Domain installer
# Allows root to connect to MariaDB without specifying password on command line
# KEEP THIS FILE SECURE — permissions must be 600
[client]
user     = root
# socket auth is default on modern MariaDB; uncomment if using password auth:
# password = "${MYSQL_ROOT_PASS}"
EOF
    chmod 600 /root/.my.cnf
    ok "/root/.my.cnf written (600)"
}

_db_tune() {
    local conf_file
    conf_file="$(os_mariadb_conf)"

    local ram_mb
    ram_mb="$(detect_ram_mb)"

    # InnoDB buffer pool: 25% of RAM, min 64 MB, max 1 GB
    local pool_mb=$(( ram_mb / 4 ))
    (( pool_mb < 64  )) && pool_mb=64
    (( pool_mb > 1024)) && pool_mb=1024

    # Max connections: conservative, can be tuned
    local max_conn=100
    (( ram_mb >= 2048 )) && max_conn=150
    (( ram_mb >= 4096 )) && max_conn=200

    # Write tuning block — idempotent via sed guard
    local tune_marker="# UH-TUNE-START"
    if grep -q "$tune_marker" "$conf_file" 2>/dev/null; then
        ok "MariaDB tuning block already present — skipping"
        return
    fi

    cat >> "$conf_file" <<EOF

${tune_marker}
[mysqld]
innodb_buffer_pool_size   = ${pool_mb}M
innodb_log_file_size      = 64M
innodb_flush_log_at_trx_commit = 2
innodb_flush_method       = O_DIRECT
max_connections           = ${max_conn}
max_allowed_packet        = 64M
query_cache_size          = 0
query_cache_type          = 0
skip_name_resolve         = ON
character_set_server      = utf8mb4
collation_server          = utf8mb4_unicode_ci
# UH-TUNE-END
EOF
    ok "MariaDB tuned: buffer_pool=${pool_mb}M, max_conn=${max_conn}"
}

db_drop_domain() {
    local dom="${1:-$DOMAIN}"
    local slug
    slug="$(slug_from_domain "$dom")"
    local db_name="${slug}_db"
    local db_user="${slug}_usr"

    mysql -e "DROP DATABASE IF EXISTS \`${db_name}\`;" 2>/dev/null && ok "Dropped database: ${db_name}" || true
    mysql -e "DROP USER IF EXISTS '${db_user}'@'localhost';" 2>/dev/null && ok "Dropped user: ${db_user}" || true
    mysql -e "FLUSH PRIVILEGES;" 2>/dev/null || true
}
