#!/usr/bin/env bash
# =============================================================================
#  modules/php.sh — Per-domain PHP-FPM pool + OPcache configuration
# =============================================================================

php_configure_pool() {
    step "Configuring PHP ${PHP_VERSION} FPM pool for ${DOMAIN}"

    os_php_fpm_sock  # sets PHP_FPM_SOCK

    local pool_dir
    pool_dir="$(os_php_fpm_pool_dir)"

    local pool_file="${pool_dir}/${DOMAIN}.conf"
    local site_user="${DOMAIN//./_}"
    site_user="${site_user:0:32}"

    # Create an isolated system user for this domain
    if ! id "$site_user" &>/dev/null; then
        useradd -r -s /bin/bash -d "${SITE_ROOT}" -c "Site user for ${DOMAIN}" "$site_user"
        # Lock the password — login only via sudo, not direct password auth
        passwd -l "$site_user" &>/dev/null || true
        ok "System user '${site_user}' created (password locked)"
    fi

    local web_user
    web_user="$(os_web_user)"

    local ram_mb
    ram_mb="$(get_total_ram_mb)"
    local cpu
    cpu="$(get_cpu_cores)"

    # Scale pool size to available RAM (roughly 40 MB per worker)
    local max_children=$(( ram_mb / 40 ))
    (( max_children < 5 ))  && max_children=5
    (( max_children > 50 )) && max_children=50

    local start_servers=$(( cpu ))
    local min_spare=$(( cpu ))
    local max_spare=$(( cpu * 2 ))
    (( max_spare > max_children )) && max_spare=$(( max_children / 2 ))

    mkdir -p "${pool_dir}"

    cat > "${pool_file}" <<PHP_POOL
; =============================================================================
; PHP-FPM pool for ${DOMAIN}
; Generated by UnderHost installer — $(date)
; =============================================================================

[${DOMAIN}]
user  = ${site_user}
group = ${site_user}

; Nginx process must be able to read the socket
listen = ${PHP_FPM_SOCK}
listen.owner = ${web_user}
listen.group = ${web_user}
listen.mode  = 0660

; Process manager
pm                   = dynamic
pm.max_children      = ${max_children}
pm.start_servers     = ${start_servers}
pm.min_spare_servers = ${min_spare}
pm.max_spare_servers = ${max_spare}
pm.max_requests      = 500

; Timeouts
request_terminate_timeout = 300

; Security
security.limit_extensions = .php

; Logging
access.log = /var/log/php-fpm/${DOMAIN}.access.log
php_flag[display_errors]  = off
php_flag[log_errors]      = on
php_value[error_log]      = /var/log/php-fpm/${DOMAIN}.error.log
php_value[session.save_path] = /var/lib/php/sessions/${DOMAIN}

; Environment
env[HOSTNAME]  = \$HOSTNAME
env[PATH]      = /usr/local/bin:/usr/bin:/bin
env[TMP]       = /tmp
env[TMPDIR]    = /tmp
env[TEMP]      = /tmp
PHP_POOL

    mkdir -p "/var/log/php-fpm"
    mkdir -p "/var/lib/php/sessions/${DOMAIN}"
    chown "${site_user}:${site_user}" "/var/lib/php/sessions/${DOMAIN}"
    chmod 700 "/var/lib/php/sessions/${DOMAIN}"

    ok "PHP-FPM pool written to ${pool_file}"
    _php_configure_opcache
}

# ---------------------------------------------------------------------------
_php_configure_opcache() {
    local ini_dir
    ini_dir="$(os_php_ini_dir)"
    local ofile="${ini_dir}/uh-opcache.ini"

    local ram_mb
    ram_mb="$(get_total_ram_mb)"
    local opcache_mem=128
    (( ram_mb >= 4096 )) && opcache_mem=256
    (( ram_mb >= 8192 )) && opcache_mem=512

    cat > "${ofile}" <<OPCACHE
; OPcache tuning — UnderHost
opcache.enable=1
opcache.enable_cli=0
opcache.memory_consumption=${opcache_mem}
opcache.interned_strings_buffer=16
opcache.max_accelerated_files=20000
opcache.revalidate_freq=60
opcache.save_comments=1
opcache.fast_shutdown=1
opcache.validate_timestamps=1
OPCACHE

    ok "OPcache configured (${opcache_mem}MB)"
}
