#!/usr/bin/env bash
# =============================================================================
#  UnderHost One-Domain — PHP-FPM Module
#  modules/php.sh
# =============================================================================

[[ -n "${_UH_PHP_LOADED:-}" ]] && return 0
_UH_PHP_LOADED=1

php_configure_pool() {
    step "Configuring PHP-FPM pool for ${DOMAIN}"

    local pool_dir
    pool_dir="$(os_php_pool_dir)"
    local pool_file="${pool_dir}/${DOMAIN}.conf"
    local socket_path

    if [[ "$OS_FAMILY" == "debian" ]]; then
        socket_path="/run/php/${DOMAIN}-fpm.sock"
    else
        socket_path="/run/php-fpm/${DOMAIN}.sock"
        mkdir -p /run/php-fpm 2>/dev/null || true
    fi

    # Isolated system user for this domain
    local sys_user
    sys_user="$(slug_from_domain "$DOMAIN" | cut -c1-16)_web"
    if ! id "$sys_user" &>/dev/null; then
        useradd -r -s /usr/sbin/nologin -d "${SITE_ROOT}" "$sys_user" 2>/dev/null \
            || useradd -r -s /sbin/nologin -d "${SITE_ROOT}" "$sys_user"
        ok "Created system user: ${sys_user}"
    fi

    # Set ownership of site root
    mkdir -p "${SITE_ROOT}/public" "${SITE_ROOT}/logs" "${SITE_ROOT}/tmp"
    chown -R "${sys_user}:${sys_user}" "$SITE_ROOT"
    chmod 750 "$SITE_ROOT"
    chmod 755 "${SITE_ROOT}/public"

    # Tune pool size by available RAM
    local ram_mb
    ram_mb="$(detect_ram_mb)"
    local max_children=$(( ram_mb / 40 ))
    (( max_children < 2  )) && max_children=2
    (( max_children > 50 )) && max_children=50
    local start_servers=$(( max_children / 4 ))
    (( start_servers < 1 )) && start_servers=1
    local min_spare=$start_servers
    local max_spare=$(( max_children / 2 ))
    (( max_spare < start_servers )) && max_spare=$start_servers

    # OPcache memory by RAM tier
    local opcache_mem=128
    (( ram_mb >= 2048 )) && opcache_mem=256
    (( ram_mb >= 4096 )) && opcache_mem=512

    cat > "$pool_file" <<EOF
; PHP-FPM pool — ${DOMAIN}
; Generated by UnderHost One-Domain installer

[${DOMAIN}]
user  = ${sys_user}
group = ${sys_user}

listen = ${socket_path}
listen.owner = nginx
listen.group = nginx
listen.mode  = 0660

; Process management
pm                   = dynamic
pm.max_children      = ${max_children}
pm.start_servers     = ${start_servers}
pm.min_spare_servers = ${min_spare}
pm.max_spare_servers = ${max_spare}
pm.max_requests      = 500

; Logging
access.log           = /var/log/php-fpm/${DOMAIN}.access.log
php_admin_value[error_log]   = /var/log/php-fpm/${DOMAIN}.error.log
php_admin_flag[log_errors]   = on
slowlog                = /var/log/php-fpm/${DOMAIN}.slow.log
request_slowlog_timeout = 10s

; Security
security.limit_extensions = .php

; PHP ini overrides
php_admin_value[open_basedir]  = ${SITE_ROOT}:/tmp:/usr/share/php:/usr/share/pear
php_admin_value[upload_tmp_dir] = ${SITE_ROOT}/tmp
php_admin_value[session.save_path] = ${SITE_ROOT}/tmp
php_flag[display_errors]       = off
php_admin_flag[expose_php]     = off
php_admin_value[memory_limit]  = 256M
php_admin_value[max_execution_time] = 60
php_admin_value[post_max_size] = 64M
php_admin_value[upload_max_filesize] = 64M

; OPcache
php_admin_value[opcache.enable]          = 1
php_admin_value[opcache.memory_consumption] = ${opcache_mem}
php_admin_value[opcache.interned_strings_buffer] = 16
php_admin_value[opcache.max_accelerated_files]   = 10000
php_admin_value[opcache.revalidate_freq]         = 60
php_admin_value[opcache.save_comments]           = 1
php_admin_value[opcache.validate_timestamps]     = 0
; Note: set validate_timestamps=1 during development
EOF

    mkdir -p /var/log/php-fpm
    touch "/var/log/php-fpm/${DOMAIN}.access.log" \
          "/var/log/php-fpm/${DOMAIN}.error.log"
    chown "$sys_user:$sys_user" \
          "/var/log/php-fpm/${DOMAIN}.access.log" \
          "/var/log/php-fpm/${DOMAIN}.error.log" 2>/dev/null || true

    # Remove the default www pool on fresh installs (security: don't run www-data globally)
    local default_pool
    default_pool="${pool_dir}/www.conf"
    if [[ -f "$default_pool" ]] && ! grep -q "^user\s*=\s*${sys_user}" "$default_pool"; then
        mv "$default_pool" "${default_pool}.disabled"
        ok "Disabled default www.conf pool"
    fi

    svc_reload "$(os_php_fpm_service)"
    ok "PHP-FPM pool configured: ${pool_file}"
    ok "  max_children=${max_children}  opcache=${opcache_mem}M"
}
