#!/usr/bin/env bash
# =============================================================================
#  modules/wordpress.sh — WordPress automated installation
# =============================================================================

# Wrapper: run WP-CLI as root with --allow-root
_wp() {
    HOME=/root wp --path="${SITE_ROOT}" --allow-root "$@"
}

wp_install() {
    step "Installing WordPress for ${DOMAIN}"

    _wp_download_core
    _wp_create_config
    _wp_set_permissions
    _wp_run_install
    [[ "$WP_HARDEN" == true ]]       && _wp_harden
    [[ "$WP_AUTO_UPDATES" == true ]] && _wp_auto_updates
    [[ "$WP_REDIS" == true ]]        && _wp_redis_cache
    ok "WordPress installed at ${SITE_ROOT}"
}

# ---------------------------------------------------------------------------
_wp_download_core() {
    info "Downloading latest WordPress"
    local tmp
    tmp="$(mktemp -d)"

    curl --fail --silent --location \
        https://wordpress.org/latest.tar.gz \
        -o "${tmp}/wp.tar.gz" \
        || die "Failed to download WordPress. Check network connectivity."

    tar -xzf "${tmp}/wp.tar.gz" -C "${tmp}" \
        || die "Failed to extract WordPress archive."

    rsync -a --delete "${tmp}/wordpress/" "${SITE_ROOT}/"
    rm -rf "$tmp"
    ok "WordPress core downloaded"
}

# ---------------------------------------------------------------------------
_wp_create_config() {
    info "Creating wp-config.php"

    # Try WordPress salt API; fall back to local generation
    local salts
    salts="$(curl --fail --silent --max-time 10 \
        https://api.wordpress.org/secret-key/1.1/salt/ 2>/dev/null || true)"

    if [[ -z "$salts" || ! "$salts" =~ "define" ]]; then
        warn "Could not reach WordPress salt API — generating salts locally"
        salts=""
        local key
        for key in AUTH_KEY SECURE_AUTH_KEY LOGGED_IN_KEY NONCE_KEY \
                   AUTH_SALT SECURE_AUTH_SALT LOGGED_IN_SALT NONCE_SALT; do
            salts+="define( '${key}', '$(gen_pass 64)' );"$'\n'
        done
    fi

    local table_prefix
    table_prefix="wp_$(gen_pass_alpha 4)_"

    local wp_cache_val="false"
    [[ "$WP_REDIS" == true ]] && wp_cache_val="true"

    cat > "${SITE_ROOT}/wp-config.php" <<WPCONFIG
<?php
// WordPress Configuration — generated by UnderHost installer $(date)

// ** Database **
define( 'DB_NAME',     '${DB_NAME}' );
define( 'DB_USER',     '${DB_USER}' );
define( 'DB_PASSWORD', '${DB_PASS}' );
define( 'DB_HOST',     'localhost' );
define( 'DB_CHARSET',  'utf8mb4' );
define( 'DB_COLLATE',  '' );

// ** Salts **
${salts}

// ** Table prefix **
\$table_prefix = '${table_prefix}';

// ** Security **
define( 'DISALLOW_FILE_EDIT',  true );
define( 'FORCE_SSL_ADMIN',     true );

// ** Performance **
define( 'WP_MEMORY_LIMIT',     '256M' );
define( 'WP_MAX_MEMORY_LIMIT', '512M' );
define( 'WP_CACHE',            ${wp_cache_val} );

// ** Updates **
define( 'WP_AUTO_UPDATE_CORE', 'minor' );

// ** URLs **
define( 'WP_HOME',    'https://${DOMAIN}' );
define( 'WP_SITEURL', 'https://${DOMAIN}' );

// ** Real cron (DISABLE_WP_CRON + system cron job) **
define( 'DISABLE_WP_CRON', true );

// ** Debugging — off in production **
define( 'WP_DEBUG',         false );
define( 'WP_DEBUG_LOG',     false );
define( 'WP_DEBUG_DISPLAY', false );
@ini_set( 'display_errors', 0 );

/* That's all, stop editing! */
if ( ! defined( 'ABSPATH' ) ) {
    define( 'ABSPATH', __DIR__ . '/' );
}
require_once ABSPATH . 'wp-settings.php';
WPCONFIG

    chmod 640 "${SITE_ROOT}/wp-config.php"
    ok "wp-config.php created (table prefix: ${table_prefix})"

    _wp_configure_cron
}

# ---------------------------------------------------------------------------
_wp_configure_cron() {
    # Real system cron replaces slow HTTP-triggered WP-Cron
    local site_user="${DOMAIN//./_}"
    site_user="${site_user:0:32}"
    local cron_file="/etc/cron.d/wp-${site_user}"

    cat > "$cron_file" <<CRONFILE
# WordPress cron for ${DOMAIN} — UnderHost installer
*/5 * * * * root /usr/local/bin/wp --path=${SITE_ROOT} --allow-root cron event run --due-now >> /var/log/wp-cron-${DOMAIN//\./-}.log 2>&1
CRONFILE
    chmod 644 "$cron_file"
    ok "WordPress system cron configured (every 5 minutes)"
}

# ---------------------------------------------------------------------------
_wp_set_permissions() {
    local site_user="${DOMAIN//./_}"
    site_user="${site_user:0:32}"
    local web_user
    web_user="$(os_web_user)"

    chown -R "${site_user}:${web_user}" "${SITE_ROOT}"
    find "${SITE_ROOT}" -type d -exec chmod 755 {} \;
    find "${SITE_ROOT}" -type f -exec chmod 644 {} \;
    chmod 640 "${SITE_ROOT}/wp-config.php"

    mkdir -p "${SITE_ROOT}/wp-content/uploads"
    chown -R "${web_user}:${web_user}" "${SITE_ROOT}/wp-content/uploads"
    chmod -R 755 "${SITE_ROOT}/wp-content/uploads"

    ok "Permissions set (owner: ${site_user}, group: ${web_user})"
}

# ---------------------------------------------------------------------------
_wp_run_install() {
    if ! command -v wp &>/dev/null; then
        warn "WP-CLI not found — complete setup at: http://${DOMAIN}/wp-admin/install.php"
        return
    fi

    info "Running WordPress core install via WP-CLI"
    _wp core install \
        --url="https://${DOMAIN}" \
        --title="${WP_TITLE:-My Site}" \
        --admin_user="${WP_ADMIN_USER}" \
        --admin_password="${WP_ADMIN_PASS}" \
        --admin_email="${WP_ADMIN_EMAIL}" \
        --skip-email \
        2>&1 | tee -a "${LOG_FILE}" \
        || die "WP-CLI install failed — see ${LOG_FILE}"

    # Remove default sample content
    _wp post    delete 1 --force 2>/dev/null || true
    _wp comment delete 1 --force 2>/dev/null || true

    # Sensible site defaults
    _wp option update blogdescription             ""        2>/dev/null || true
    _wp rewrite structure                         '/%postname%/' 2>/dev/null || true
    _wp option update default_comment_status      "closed"  2>/dev/null || true
    _wp option update default_ping_status         "closed"  2>/dev/null || true
    _wp option update close_comments_for_old_posts 1        2>/dev/null || true
    _wp option update timezone_string             "UTC"     2>/dev/null || true

    # Remove unused bundled plugins
    _wp plugin delete hello akismet 2>/dev/null || true

    ok "WordPress installed and configured"
}

# ---------------------------------------------------------------------------
_wp_harden() {
    info "Applying WordPress hardening"

    # Remove information-leaking files
    local f
    for f in readme.html license.txt wp-config-sample.php; do
        rm -f "${SITE_ROOT}/${f}" 2>/dev/null || true
    done

    # Nginx-format .htaccess for portability
    cat > "${SITE_ROOT}/.htaccess" <<'HTACCESS'
# BEGIN WordPress
<IfModule mod_rewrite.c>
RewriteEngine On
RewriteBase /
RewriteRule ^index\.php$ - [L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule . /index.php [L]
</IfModule>
# END WordPress
HTACCESS

    ok "WordPress hardening applied"
}

# ---------------------------------------------------------------------------
_wp_auto_updates() {
    # WP_AUTO_UPDATE_CORE is set in wp-config.php; confirm via WP-CLI if present
    command -v wp &>/dev/null \
        && _wp config set WP_AUTO_UPDATE_CORE minor --raw 2>/dev/null || true
    ok "WordPress auto-updates: minor/security releases enabled"
}

# ---------------------------------------------------------------------------
_wp_redis_cache() {
    command -v wp &>/dev/null \
        || { warn "WP-CLI not found — skip Redis cache setup"; return; }

    info "Configuring Redis object cache"

    _wp plugin install redis-cache --activate 2>&1 | tee -a "${LOG_FILE}" || {
        warn "Could not install redis-cache plugin automatically"
        return
    }

    # Add Redis constants if not already present
    if ! grep -q "WP_REDIS_HOST" "${SITE_ROOT}/wp-config.php"; then
        sed -i "/\/\* That's all/i \\
\\/\\/ ** Redis object cache **\\
define( 'WP_REDIS_HOST', '127.0.0.1' );\\
define( 'WP_REDIS_PORT', 6379 );\\
define( 'WP_REDIS_TIMEOUT', 1 );\\
define( 'WP_REDIS_READ_TIMEOUT', 1 );\\
define( 'WP_REDIS_DATABASE', 0 );\\
" "${SITE_ROOT}/wp-config.php"
    fi

    _wp redis enable 2>/dev/null || true
    ok "Redis object cache installed and enabled"
}
